import Head from 'next/head'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import { useState } from 'react';
import Image from 'next/image';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  const [data, updateData] = useState<{ UID: number, value: number }[]>([]);


  fetch("vercel-deploy-test-psi-eosin.vercel.app/api/recive", { method: "POST", credentials: "same-origin" }).then(res => {

    res.json().then(data => {

      updateData(data);

    })

  })

  return (
    <>
      <Head>
        <title>Vercel deploy test</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <h1>Vercel deploy test</h1>
        {data.map((el, i) => {

          return <div key={i} >{`element UID:#${el.UID} element value:${el.value}`}</div>

        })}
        <Image src={"/3.webp"} alt='something'></Image>
        <Image src={"/4.webp"} alt='something'></Image>
        <Image src={"/5.webp"} alt='something'></Image>
      </main>
    </>
  )
}
